### ISSUE TITLE
Replace 32bits integer for 64bits ones in ListIndicesResponse

### ISSUE THREAD

**Issue by aseure** [algolia/algoliasearch-client-csharp#615]
As reported by a customer on support, when calling `ListIndices[Async]`, deserialization is throwing an exception because of an integer above 2^31 which cannot fit in `int` fields of `ListIndicesResponse.FileSize`. Same issue may happen with other fields so it's probably better to change them all for 64bits values. (those values being positives, we may want to use `uint` which covers `[0; 2^32[` range.

**Comment by aseure** [comment]
For the record, here was the full stack trace from the original support ticket:

```
JSON integer 2626091034 is too large or small for an Int32. Path 'items[0].fileSize', line 1, position 177.
StackTrace :
at Newtonsoft.Json.JsonTextReader.ParseReadNumber(ReadType readType, Char firstChar, Int32 initialPosition) in /_/Src/Newtonsoft.Json/JsonTextReader.cs:line 2009
at Newtonsoft.Json.JsonTextReader.ReadNumberValue(ReadType readType) in /_/Src/Newtonsoft.Json/JsonTextReader.cs:line 958
at Newtonsoft.Json.JsonTextReader.ReadAsInt32() in /_/Src/Newtonsoft.Json/JsonTextReader.cs:line 462
at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter) in /_/Src/Newtonsoft.Json/JsonReader.cs:line 1197
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 2304
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 485
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 1663
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 875
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 1032
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 2386
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 485
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 167
at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType) in /_/Src/Newtonsoft.Json/JsonSerializer.cs:line 907
at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader) in /_/Src/Newtonsoft.Json/JsonSerializer.cs:line 873
at Algolia.Search.Serializer.SerializerHelper.Deserialize[T](Stream stream, JsonSerializerSettings settings)
at Algolia.Search.Transport.HttpTransport.ExecuteRequestAsync[TResult,TData](HttpMethod method, String uri, CallType callType, TData data, RequestOptions requestOptions, CancellationToken ct)
at Algolia.Search.Transport.HttpTransport.ExecuteRequestAsync[TResult](HttpMethod method, String uri, CallType callType, RequestOptions requestOptions, CancellationToken ct)
at Algolia.Search.Clients.SearchClient.ListIndicesAsync(RequestOptions requestOptions, CancellationToken ct) 
```

**Comment by Ant-hem** [comment]
Good catch! For 64bits integer we should use `long` instead of `int`.

**Comment by olihou** [comment]
To be sure why not use unsigned type like "ulong" ?

**Comment by Ant-hem** [comment]
> To be sure why not use unsigned type like "ulong" ?

Hey!

IIRC `ulong` is [not CLS compliant](https://docs.microsoft.com/en-us/dotnet/api/system.uint64?view=netcore-2.2). So I'd rather avoid it. Further more, if we look at the [API ref](https://www.algolia.com/doc/api-reference/api-methods/list-indices/?language=php#method-response-filesize) `FileSize` is supposed to be an int, so it's not likely to exceed 64bits int :)

**Comment by aseure** [comment]
From a semantic point of view, I'd rather use unsigned integers here but if by mistake the API is returning a negative value, I'd rather keep the signed version.

`long` is 64bits signed integer in C#, meaning that it covers the range [-9,223,372,036,854,775,808; 9,223,372,036,854,775,807]` which is perfectely good enough for us in that case.

@Ant-hem PR ready for review: https://github.com/algolia/algoliasearch-client-csharp/pull/616.
