### ISSUE TITLE
Use other type than string for ObjectID

### ISSUE THREAD

**Issue by Rickos99** [algolia/algoliasearch-client-csharp#855]
- Algolia Client Version: 6.16.0
- Language Version: .NET 8.0

### Description

I want to assign Id of type `GUID` to ObjectID without adding a second property.

### Steps To Reproduce

1. Create the following class

    ```cs
    public class A
    {
        [JsonProperty(PropertyName = "objectID")]
        public Guid Id { get; set; }
    
        public string Data {get; set}
    }
    ```
2. Create instance of `A`
3. Use `Algolia.Search.Clients.SearchIndex.SaveObjectAsync(...)` and save it to an index.
   
   This will result in

```
Algolia.Search.Exceptions.AlgoliaException: The ObjectID property or the JsonPropertyAttribute with name='objectID' must be a string
   at Algolia.Search.Utils.AlgoliaHelper.EnsureObjectID[T]()
   at Algolia.Search.Clients.SearchIndex.SaveObjectsAsync[T](IEnumerable`1 data, RequestOptions requestOptions, CancellationToken ct, Boolean autoGenerateObjectId)
   at Algolia.Search.Clients.SearchIndex.SaveObjectAsync[T](T data, RequestOptions requestOptions, CancellationToken ct, Boolean autoGenerateObjectId)
   ...
```

### Solution

```cs
public class A
{
    public Guid Id { get; set; }

    public string ObjectID { get => Id.ToString(); }

    public string Data {get; set}
}
```

### Proposal

[This](https://github.com/algolia/algoliasearch-client-csharp/blob/616fcbac403791d15153f2e48d1c8a7b9e37d511/src/Algolia.Search/Utils/AlgoliaHelper.cs#L83) is where the exception is thrown. Would it make sense to allow other types such as `GUID` in the `ObjectID` property or is there a reason for it to be string?

**Comment by morganleroi** [comment]
Apologies for the late response and thanks for posting this issue @Rickos99. 

Your solution is the best one for the 6.x version of the client.

We launched a 7.x new client (Currently in beta) and you can now send the `ObjectID` with a Guid.

```csharp
    var saved = await _client.SaveObjectAsync(DefaultIndex,
      new { ObjectID = Guid.NewGuid(), value = "test", otherValue = "otherValue" });
```
